version: '3'
services:
  webserver:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./environment/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
  php:
    build: ./environment/
    expose:
      - 9000
      - 9003
    volumes:
      - ./src:/var/www/html
